/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface PasteView {
    id: string;
    title: string;
    paymentStatus: string;
    expiresAt: bigint;
    contentType: string;
    createdAt: bigint;
    uploadComplete: boolean;
    sizeBytes: bigint;
}
export interface InitPasteResponse {
    expiresAt: bigint;
    chain: string;
    chunksExpected: bigint;
    paymentAddress: string;
    pasteId: string;
    expectedAmount: string;
}
export interface InitPasteRequest {
    durationDays: bigint;
    title: string;
    contentType: string;
    totalSize: bigint;
    firstChunk: Uint8Array;
    paymentChain: string;
}
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<[string, string]>;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<[string, string]>;
    status_code: number;
}
export interface backendInterface {
    confirmPayment(pasteId: string, txHash: string): Promise<boolean>;
    createPaste(req: {
        durationDays: bigint;
        title: string;
        content: Uint8Array;
        contentType: string;
        paymentChain: string;
    }): Promise<{
        expiresAt: bigint;
        chain: string;
        paymentAddress: string;
        pasteId: string;
        expectedAmount: string;
    }>;
    deletePaste(pasteId: string): Promise<boolean>;
    gc(): Promise<bigint>;
    getChunk(pasteId: string, index: bigint): Promise<Uint8Array | null>;
    getChunkCount(pasteId: string): Promise<bigint | null>;
    getLastTxHash(): Promise<string>;
    getLastVerifyError(): Promise<string>;
    getPasteContent(pasteId: string): Promise<Uint8Array | null>;
    getPasteInfo(pasteId: string): Promise<PasteView | null>;
    http_request(req: HttpRequest): Promise<HttpResponse>;
    initPaste(req: InitPasteRequest): Promise<InitPasteResponse>;
    myPastes(): Promise<Array<PasteView>>;
    stats(): Promise<{
        maxStorageBytes: bigint;
        totalStorageBytes: bigint;
        totalPastes: bigint;
    }>;
    uploadChunk(pasteId: string, chunk: Uint8Array): Promise<{
        complete: boolean;
        chunksReceived: bigint;
    }>;
}
import type { PasteView as _PasteView } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async confirmPayment(arg0: string, arg1: string): Promise<boolean> {
        const result = await this.actor.confirmPayment(arg0, arg1);
        return result;
    }
    async createPaste(arg0: {
        durationDays: bigint;
        title: string;
        content: Uint8Array;
        contentType: string;
        paymentChain: string;
    }): Promise<{
        expiresAt: bigint;
        chain: string;
        paymentAddress: string;
        pasteId: string;
        expectedAmount: string;
    }> {
        const result = await this.actor.createPaste(arg0);
        return result;
    }
    async deletePaste(arg0: string): Promise<boolean> {
        const result = await this.actor.deletePaste(arg0);
        return result;
    }
    async gc(): Promise<bigint> {
        const result = await this.actor.gc();
        return result;
    }
    async getChunk(arg0: string, arg1: bigint): Promise<Uint8Array | null> {
        const result = await this.actor.getChunk(arg0, arg1);
        return from_candid_opt_n1(result);
    }
    async getChunkCount(arg0: string): Promise<bigint | null> {
        const result = await this.actor.getChunkCount(arg0);
        return from_candid_opt_n2(result);
    }
    async getLastTxHash(): Promise<string> {
        const result = await this.actor.getLastTxHash();
        return result;
    }
    async getLastVerifyError(): Promise<string> {
        const result = await this.actor.getLastVerifyError();
        return result;
    }
    async getPasteContent(arg0: string): Promise<Uint8Array | null> {
        const result = await this.actor.getPasteContent(arg0);
        return from_candid_opt_n1(result);
    }
    async getPasteInfo(arg0: string): Promise<PasteView | null> {
        const result = await this.actor.getPasteInfo(arg0);
        return from_candid_opt_n3(result);
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        const result = await this.actor.http_request(arg0);
        return result;
    }
    async initPaste(arg0: InitPasteRequest): Promise<InitPasteResponse> {
        const result = await this.actor.initPaste(arg0);
        return result;
    }
    async myPastes(): Promise<Array<PasteView>> {
        const result = await this.actor.myPastes();
        return result;
    }
    async stats(): Promise<{
        maxStorageBytes: bigint;
        totalStorageBytes: bigint;
        totalPastes: bigint;
    }> {
        const result = await this.actor.stats();
        return result;
    }
    async uploadChunk(arg0: string, arg1: Uint8Array): Promise<{
        complete: boolean;
        chunksReceived: bigint;
    }> {
        const result = await this.actor.uploadChunk(arg0, arg1);
        return result;
    }
}
function from_candid_opt_n1(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(value: [] | [_PasteView]): PasteView | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
