/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const PasteView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'expiresAt' : IDL.Int,
    'contentType' : IDL.Text,
    'createdAt' : IDL.Int,
    'uploadComplete' : IDL.Bool,
    'sizeBytes' : IDL.Nat,
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'status_code' : IDL.Nat16,
  });
  const InitPasteRequest = IDL.Record({
    'durationDays' : IDL.Nat,
    'title' : IDL.Text,
    'contentType' : IDL.Text,
    'totalSize' : IDL.Nat,
    'firstChunk' : IDL.Vec(IDL.Nat8),
    'paymentChain' : IDL.Text,
  });
  const InitPasteResponse = IDL.Record({
    'expiresAt' : IDL.Int,
    'chain' : IDL.Text,
    'chunksExpected' : IDL.Nat,
    'paymentAddress' : IDL.Text,
    'pasteId' : IDL.Text,
    'expectedAmount' : IDL.Text,
  });
  
  return IDL.Service({
    'confirmPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'createPaste' : IDL.Func(
        [
          IDL.Record({
            'durationDays' : IDL.Nat,
            'title' : IDL.Text,
            'content' : IDL.Vec(IDL.Nat8),
            'contentType' : IDL.Text,
            'paymentChain' : IDL.Text,
          }),
        ],
        [
          IDL.Record({
            'expiresAt' : IDL.Int,
            'chain' : IDL.Text,
            'paymentAddress' : IDL.Text,
            'pasteId' : IDL.Text,
            'expectedAmount' : IDL.Text,
          }),
        ],
        [],
      ),
    'deletePaste' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'gc' : IDL.Func([], [IDL.Nat], []),
    'getChunk' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getChunkCount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getLastTxHash' : IDL.Func([], [IDL.Text], ['query']),
    'getLastVerifyError' : IDL.Func([], [IDL.Text], ['query']),
    'getPasteContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getPasteInfo' : IDL.Func([IDL.Text], [IDL.Opt(PasteView)], ['query']),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'initPaste' : IDL.Func([InitPasteRequest], [InitPasteResponse], []),
    'myPastes' : IDL.Func([], [IDL.Vec(PasteView)], ['query']),
    'stats' : IDL.Func(
        [],
        [
          IDL.Record({
            'maxStorageBytes' : IDL.Nat,
            'totalStorageBytes' : IDL.Nat,
            'totalPastes' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'uploadChunk' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Record({ 'complete' : IDL.Bool, 'chunksReceived' : IDL.Nat })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };