/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'status_code' : number,
}
export interface InitPasteRequest {
  'durationDays' : bigint,
  'title' : string,
  'contentType' : string,
  'totalSize' : bigint,
  'firstChunk' : Uint8Array,
  'paymentChain' : string,
}
export interface InitPasteResponse {
  'expiresAt' : bigint,
  'chain' : string,
  'chunksExpected' : bigint,
  'paymentAddress' : string,
  'pasteId' : string,
  'expectedAmount' : string,
}
export interface PasteView {
  'id' : string,
  'title' : string,
  'paymentStatus' : string,
  'expiresAt' : bigint,
  'contentType' : string,
  'createdAt' : bigint,
  'uploadComplete' : boolean,
  'sizeBytes' : bigint,
}
export interface _SERVICE {
  'confirmPayment' : ActorMethod<[string, string], boolean>,
  'createPaste' : ActorMethod<
    [
      {
        'durationDays' : bigint,
        'title' : string,
        'content' : Uint8Array,
        'contentType' : string,
        'paymentChain' : string,
      },
    ],
    {
      'expiresAt' : bigint,
      'chain' : string,
      'paymentAddress' : string,
      'pasteId' : string,
      'expectedAmount' : string,
    }
  >,
  'deletePaste' : ActorMethod<[string], boolean>,
  'gc' : ActorMethod<[], bigint>,
  'getChunk' : ActorMethod<[string, bigint], [] | [Uint8Array]>,
  'getChunkCount' : ActorMethod<[string], [] | [bigint]>,
  'getLastTxHash' : ActorMethod<[], string>,
  'getLastVerifyError' : ActorMethod<[], string>,
  'getPasteContent' : ActorMethod<[string], [] | [Uint8Array]>,
  'getPasteInfo' : ActorMethod<[string], [] | [PasteView]>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'initPaste' : ActorMethod<[InitPasteRequest], InitPasteResponse>,
  'myPastes' : ActorMethod<[], Array<PasteView>>,
  'stats' : ActorMethod<
    [],
    {
      'maxStorageBytes' : bigint,
      'totalStorageBytes' : bigint,
      'totalPastes' : bigint,
    }
  >,
  'uploadChunk' : ActorMethod<
    [string, Uint8Array],
    { 'complete' : boolean, 'chunksReceived' : bigint }
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];